### ISSUE TITLE
Issue with finished programs and watched status

### ISSUE THREAD

**Issue by iAmRenzo** [4np/UitzendingGemist#11]
I really love the option "kijk verder" to catch up on favourite shows I didn't have seen but there is a thing going on. There are shows I have seen (on your app).
When I investigated the situation it dawned on me that when you watch a show to the end, it goes back to the start. If you go back to the menu you leave that show at 0:00 and maybe the app sees that as not shown.
Option would be that if a show ends, you automatically go back to the menu, instead of 0:00.

**Comment by 4np** [comment]
Hi Renzo, I have actually noticed exactly the same issue causing the show to become `unwatched` even though you watched it to the end. I will take a look...

**Comment by 4np** [comment]
Fixed in [Release 1.0.1](https://github.com/4np/UitzendingGemist/releases/tag/1.0.1)
