### ISSUE TITLE
Easily mark as watched

### ISSUE THREAD

**Issue by iAmRenzo** [4np/UitzendingGemist#13]

**Comment by iAmRenzo** [comment]
I love the 'what to watch' section of my favorite programs. There is just one thing: episodes I've seen live will be added.
I guess there isn't a way to mark these as watched because the gemist-entry isn't yet available.
To click on an episode. Browse to the button 'mark as watched' and go back is a little too much.
Infuse presents this menu on a long press. Would be a great idea to make an episode or whole season watched.
![](http://i.imgur.com/rGVCOAh.jpg)

**Comment by 4np** [comment]
@iAmRenzo, I am indeed running into that myself as well and I think it might be a good improvement. I will take a look at this whenever I have some spare time 👍
