### ISSUE TITLE
Request: link to youtube channels

### ISSUE THREAD

**Issue by dizzzz** [4np/UitzendingGemist#14]
Quite some NPO programs do have a kinda archive on Youtube (think of Lubach op Zondag, Tegenlicht, etc). Would it make sense to have a link to these programs in the Youtube app?

**Comment by 4np** [comment]
I'm contemplating what to do with this request. Instead of relying on data from the NPO's APIs this particular feature would require a curated list of programs and youtube channels / accounts. While this can for example be solved by storing a JSON file on GitHub and accepting pull requests to extend the document, this however completely relies on an active community to provide reliable content. The other issue is that providing a YouTube link would also make you leave the app and switch to YouTube instead. How do other people feel about this feature?

**Comment by doedje** [comment]
In regards to 'how do I feel about this feature' I will share my feelings with you:

1) community driven input on GitHub:
I think this is indeed a smart idea. I imagine a setting which does or does not include this content in the app (the default might be discussed later...) It should be obvious to end-users that the content is community driven and that they can participate in keeping that JSON reliable.

2) switching to another app:
I wouldn't mind. For example, Sinterklaas journaal, does mention their website at the end of the show, where you can find games, kleurplaten and stuff. Sadly appleTV does not have a native browser, but just imagine having a button in the UI that says "Open website", right next to where it says "play", "to program", "mark as unseen", "favorite".
I wouldn't mind such a button to open a browser to show me the Sinterklaas journaal website. 
And in that same way I would not mind switching to the YouTube app when I press a "Open youtube channel" button.

**Comment by dizzzz** [comment]
on my phone the app switching (and going back!) is frequently done; I am very willing to (actively) contribute to this "curated list of programs and youtube channels / accounts"

**Comment by 4np** [comment]
Added initial YouTube support, work in progress... It uses the curated list at the [Additional Resources](https://github.com/4np/NPOKitResources/) project to show the YouTube button and fetch videos.

![screen shot 2016-11-18 at 22 32 39](https://cloud.githubusercontent.com/assets/1049693/20447426/08b7e0da-addf-11e6-90a3-fc3a094a8d92.png)

![screen shot 2016-11-18 at 22 32 55](https://cloud.githubusercontent.com/assets/1049693/20447425/08aaed3a-addf-11e6-88f8-346ed87f6ca9.png)

**Comment by 4np** [comment]
Finalized the YouTube channel support and released it in [version 1.1.0](https://github.com/4np/UitzendingGemist/releases/tag/1.1.0).

Please [contribute new channels](https://github.com/4np/NPOKitResources) when you know of some...

_Note: website support is currently not feasible as tvOS does not have a built in browser. There are [some initiatives](https://github.com/jvanakker/tvOSBrowser) that resort to private APIs but this all feels a bit wonky (usability wise as well as it's basically a hack) so I am not including that._

Closing...

**Comment by dizzzz** [comment]
Great work, thnx!
