### ISSUE TITLE
Enhancement/design: episode information screen

### ISSUE THREAD

**Issue by iAmRenzo** [4np/UitzendingGemist#2]
I don't know if you're open for requests or things but I do post it here (hope you don't mind).

I like your app very much but when I saw the episode information screen I thought the design is a little non-Apple TV'ish.
Below is the same screen for Infuse and for an other Uitzending Gemist app.
![img_2227](https://cloud.githubusercontent.com/assets/1183790/11928548/b2a33020-a7d4-11e5-8c2b-ea5853173f61.jpg)
![img_2228](https://cloud.githubusercontent.com/assets/1183790/11928549/b2cd3172-a7d4-11e5-9887-aa1e9a8a45d4.jpg)

**Comment by 4np** [comment]
Hi Renzo,

You've got a point :+1: Thanks for the feedback :) If I have some spare time I will take a look at the episode screen :)

**Comment by 4np** [comment]
Hey Renzo, I am working on a complete overhaul of the app. If you have more thoughts let me know :)

**Comment by iAmRenzo** [comment]
I do have some. I don't want to be demanding. But if you want my thoughts, I'll share them!

**Comment by 4np** [comment]
Shoot :+1:  And I'll see if I can include any :)

**Comment by 4np** [comment]
Fixed in [Release 0.1.0](https://github.com/4np/UitzendingGemist/releases/tag/0.1.0)...
