### ISSUE TITLE
Older videos missing

### ISSUE THREAD

**Issue by alloy** [4np/UitzendingGemist#23]
Hey, great app, thanks a bunch!

I was wondering why it appears that only recent videos are available? Is it because you’re using the API and that is limited compared to the offering on the website?

**Comment by alloy** [comment]
I just compared to the NPO app and see that the data is the same there, so I assume that that’s the API you’re using as well. Bummer.

**Comment by 4np** [comment]
Thanks! Good to hear you like it ;)

The episodes you see are indeed those that are returned by the API. However, having said that, when you use the app for a longer period of time and you have a number of favourite programs, the metadata of the episodes for those programs will be cached locally. That means that while the episode may not return the older episodes anymore, you might _still_ be able to watch those episodes (unless the NPO remove them altogether).

**Comment by alloy** [comment]
Interesting. Ok, well, that answers my question then, thanks again.
