### ISSUE TITLE
NPO Start Plus

### ISSUE THREAD

**Issue by iAmRenzo** [4np/UitzendingGemist#25]
I have a NPO Start Plus subscription, but the NPO is still lacking an Apple TV app.
Is there a way to build the higher quality streams an such into the app? Does NPO provide an API for that?

Would be awesome!
_Now that side loading can be done wirelessly I am back in the game of side loading!_

**Comment by 4np** [comment]
Hey Renzo,

The app is actually using adaptive streams, which means that your stream quality will adapt to your connection speed. You _should_ be able to see HD like quality if your connection allows it (_except_ for the themed channels which don't have high quality streams).

Side note is that the NPO has moved to a new authenticated API (see comments on #24) which basically means the current API has been deprecated. While it currently still works, the NPO can decide to kill the API whenever they like, which means the app will stop working.

For now we're still good, let's hope it stays that way...

Cheers, Jeroen

**Comment by iAmRenzo** [comment]
I know that is uses adaptive streaming, but the app doesn't know if I am a paid subscriber, right? I thought the free subscription isn't HD at all.

Isn't there a new API to use?

**Comment by 4np** [comment]
The free streams also have HD quality, except for the themed channels. There is a new API, but that one requires an API token only the NPO will give out (and invalidate). I did some tests and while I have found an API key, the NPO can revoke it anytime they would like to. When I have time I need to investigate whether or not it's worth investing time into...
