### ISSUE TITLE
"Tips" page shows only "Kijk verder:"

### ISSUE THREAD

**Issue by FrnklyN** [4np/UitzendingGemist#26]
![screen shot 2017-10-15 at 13 29 23](https://user-images.githubusercontent.com/15732484/31584343-fbbd94b0-b1ac-11e7-85fa-6cef83b72a57.png)

**Comment by 4np** [comment]
Hey Frank,

Like mentioned in #24 and #25, the NPO has deprecated the API and is not updating the tips anymore. So unfortunately there is not a whole lot to do about it... 

Cheers
