### ISSUE TITLE
import CocoaLumberjack # no such module '...'

### ISSUE THREAD

**Issue by kreativ-software** [4np/UitzendingGemist#28]
Hi,
I can't get the project to build.
I get no such module for the pods in 'YouTubeViewController.swift'.
Any ideas?
Tried to install the pods again, but no success.
Any help is appreciated.

**Comment by 4np** [comment]
The dependencies are bundled in the project, so you _should not_ see such problems. Try clearing out your derived data and recompile (e.g. `rm -rf ~/Library/Developer/Xcode/DerivedData/`).

**Comment by blubber** [comment]
For me the issue occured when opening the `.xcodeproj` file. As the readme says, you need to open the `.xcworkspace` in XCode.

**Comment by kreativ-software** [comment]
ooooo, *facepalm*

**Comment by 4np** [comment]
Hah 👍 Nice catch blubber ;)
