### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by TonVH** [4np/UitzendingGemist#5]
Just my 2 cents.

Just love the app. It's one worth to pay for (as opposed to the rubbish). A few idea's (don't forget I have no idea at all what is possible or not):
-  The station selection screen should really be like someone else showed .
  ![e348acfc-e2c9-11e5-8665-15acd2417a3b 2](https://cloud.githubusercontent.com/assets/4800093/14845035/f1b3f538-0c5b-11e6-82c0-0d3357fa8118.jpg)
  Looks great this way.
-  Is it (im)possible to add the RTL & SBS stations? No idea whether they broadcast on the Internet.
-   EPG (like shown) would be very nice.
  ![scrnprnt 686](https://cloud.githubusercontent.com/assets/4800093/14845096/57801f72-0c5c-11e6-9a5a-a69914fa2bdc.jpg)
-  Enable the subtitling of Teletext (page 888)

Remember: it is already a great app.

**Comment by 4np** [comment]
Hi Antonio, 

Thanks for sharing your thoughts 👍 

In the current iteration of the app the 'live tv' screen has been greatly improved showing previews (where possible) and what's currently on and coming up.

My focus is initially the NPO, maybe I will look into the commercial channels at some point, but right now I am targeting at making the app working as good as possible with the NPO / Uitzending Gemist. Perhaps after that I might look into the commercial channels.

While the EPG data for the NPO and regional broadcasters is freely available as open data, those of the other channels is not and actually needs to be _bought_ under a subscription license. I _might_ include EPG data at some point, but again the focus is first making this app work as good a possible and fill all the needs of an 'uitzending gemist' service.

Teletext is old and obsolete technology which I do not aim to include in this app :) 

Closing this for now...
