### ISSUE TITLE
No such module

### ISSUE THREAD

**Issue by iAmRenzo** [4np/UitzendingGemist#7]
How do I fix this error?
(I am on macOS Sierra without the new Xcode beta)
<img width="1141" alt="schermafbeelding 2016-08-20 om 13 22 48" src="https://cloud.githubusercontent.com/assets/1183790/17830852/43e23130-66d9-11e6-9f5f-7fb1ed134587.png">

**Comment by 4np** [comment]
It should just work as all the dependencies are in GitHub. Try `clean` and `build`:

<img width="200" alt="screen shot 2016-08-21 at 13 24 34" src="https://cloud.githubusercontent.com/assets/1049693/17836894/9f69b784-67a2-11e6-9fde-fab91dc9d988.png">

ps. I am still on El Capitan. It probably will not work on the new tvOS beta as the project still needs to be updated to Swift 3

**Comment by iAmRenzo** [comment]
Sorry, it doesn't. It keeps saying no such module.
I just did a new git clone of the project.

**Comment by 4np** [comment]
Can you try with the latest code? I just pushed an update to the pods (e.g. dependencies). If it still does not work, can you try to do the following?

### Delete the derived data

Xcode derived data sometimes becomes corrupt, causing builds to fail. Quit Xcode and run the following in terminal:

```
rm -rf ~/Library/Developer/Xcode/DerivedData
```

Try to build again in Xcode. 

## If that _still_ did not work, try this:

### Install cocoapods 1.0.1

[Cocoapods](https://cocoapods.org) is a dependency manager. All the dependencies are in Git so you _should_ have them, but try this to be absolutely sure you have all dependencies:

```
sudo gem install cocoapods
```

### install dependencies

When done, open terminal, _cd_ into your project folder (if you followed the readme it should be here):

```
cd ~/Developer/tvOS/UitzendingGemist
```

 and install the dependencies:

```
pod install
```

Then try to build again in Xcode...

**Comment by iAmRenzo** [comment]
I tried to build the former version: got the same error. Or it doesn't work on macOS Sierra. Or the installing of the beta remove some things. I will try your solution... :)

**Comment by iAmRenzo** [comment]
I can confirm this is a lot of work... which I didn't have the first time.
To install cocoapods I need to update ruby which needs rvm, which won't work because of an ownership problem on a folder... why is this so hard while it wasn't the first time?

And now I am stuck on a previous version and I see the "there is an update"-screen everytime I start the app...:(

**Comment by 4np** [comment]
Well, it _should not_ be hard as it is supposed to work without doing the cocoapods steps (as the dependencies are already in the codebase). It's merely a way to debug the issue on your end. Additionally there seems to be an issue with Xcode 8. A lot of developers seem to experience issues so let's see how Apple addresses that issue (hopefully soon)...

**Comment by iAmRenzo** [comment]
But how can I lose the UIColor_Hex_Swift module!? I didn't change anything.
I downloaded Xcode 8, and the same error exists.

**Comment by 4np** [comment]
Renzo, please check [version 1.0.0](https://github.com/4np/UitzendingGemist/releases/tag/1.0.0) using Xcode 8 and apple tv running tvOS 10. It should definitely work without doing the cocoapods steps... The Hex Color pod has also seen updates in this version and I am confident it should work out for you as well.
