### ISSUE TITLE
Assets failing to load?

### ISSUE THREAD

**Issue by JurreCl** [4np/UitzendingGemist#8]
Hi, 

Somehow all of a sudden the app fails to load for me. I've tried different versions, but I keep ending up with the same results. 
In both the simulator AND the actual TV all thats displayed is this: 
<img width="960" alt="screenshot 2016-08-27 10 56 54" src="https://cloud.githubusercontent.com/assets/418230/18026380/0b029ec4-6c45-11e6-9797-2e62d96e3fe0.png">

Furthermore the app is unresponsive, do you have any idea what could be the cause of this?

**Comment by 4np** [comment]
I am sorry to hear you are having issues. My guess is that is might have to do with a small underlying datamodel change. Can you try to first delete the app from your Apple tv and then re-install? If your simulator is also unresponsive, perhaps there was an outage with the NPO API's (or your internet provider)? Do any other people experience the same issue?

**Comment by JurreCl** [comment]
Re-installing didn't resolve the issue for me, for both the simulator and device itself.
On the simulator I even did a full restore to make sure there weren't any leftovers left. My ISP doesn't have any outage that I known of at the moment. I can confirm that uitzendinggemist.nl does work from this location. Not sure where I can find the status of their API, but I assume they use the same API as we are using.

**Comment by 4np** [comment]
Hmm, that's odd. The app uses the same API as the iOS app, which is different from what the website uses although there is overlap regarding the video player. Unfortunately I am sorry to say I can not take a closer look as I am out of the country without laptop. Perhaps you could find some more clues by taking a closer look at the console output (the bottom window in Xcode) and check for errors / warnings.

**Comment by BartHM** [comment]
I compiled the app for the first time a week ago (20-8) and got the same result. It compiles ok with a few warnings for the .png files.
BTW NPO announced some major changes for their apps and web presence, hopefully the impact on this project is not too big.

**Comment by JurreCl** [comment]
Yeah, as BartHM said, all the warnings I get are related to the images. I'll see if I can find time to debug further with some breakpoints, but for now I'm clueless as to where it'll try to connect to the NPO API.

**Comment by TookiTheGreat** [comment]
I have the same experience. Rebuilt everything from scratch but got stuck when running the simulator. Since my wife (who is Dutch) loves watching Dutch TV on the Apple TV I didn't have the heart to try running it on the actual device. The previous version runs fine, but we do notice the images can take a long time to load, which slows down navigation, as there is no visible feedback when browsing through programs that do not yet have their image loaded in.
But we love what you're doing with the app. We have only one feature request: a search by keyword function. My wife doesn't always remember the exact title of a program and would love to just type in a keyword or two and get a list of matches. It's minor, not a show stopper at all. For the rest, nothing but praise.

**Comment by mischamol** [comment]
I am having the same problems. Next to some assets not loading warning, I also get a warning regarding swiftlint not being installed. Haven't had any time to do some debugging. 
Anyone else figured this out yet?

PS: love the app

**Comment by kreativ-software** [comment]
Same issue here. I took the master. Is there a difference with the 0.4.0 tag?

**Comment by kreativ-software** [comment]
Er komen wel tips binnen. Na een tijdje zitten daar 20 items in. Maar hij renderd ze niet. En de bediening reageert ook niet. Zowel simulator als device

**Comment by kreativ-software** [comment]
```
    // re-order cells (if needed)
```

In UICollectionView blijft ie hangen

**Comment by 4np** [comment]
Hmmm that sounds like a possible bug in the sorting logic. Unfortunately I am on a camping trip in France with just my phone with me (and some terrible internet connection :)). I'll be back home in about a week and a half so I'll take a closer look at the issue. If anybody is up for it to find a solution, perhaps try commenting out the re-order logic. Net networking stuff is inside NPOKit (which is the networking library and is an Xcode project by itself). Sorry for the bug, I hope you can holdout for another 1.5 weeks!

Ps. Thanks for the compliments, it's always good to hear your open source efforts are appreciated ;)

**Comment by 4np** [comment]
Oh, and keep in mind the code is not yet compatible with the new tvOS that will be released soon. I still need to convert the code to the new syntax.

**Comment by kreativ-software** [comment]
I just commented out the while loop after that comment. Everything seems fine. At least I can watch the programs!
I don't know if I have the time to really look into it, if so, I'll do a pull-request.

-- Good to know!

**Comment by 4np** [comment]
Could you all -in the meantime- let me know if you upgrades to the latest version or if this was your first intallation? In case of an upgrade, did you favorite programs in the previous version or did you not favorite anything?

**Comment by kreativ-software** [comment]
This was my first installation.

**Comment by TookiTheGreat** [comment]
I upgraded from version 3.0. I had not favorited anything before.

**Comment by mischamol** [comment]
This was a fresh installation

**Comment by 4np** [comment]
Allright, thanks :)

**Comment by 4np** [comment]
Unfortunately it's taking more time than anticipated. Swift 3 has quite _a lot_ of source breaking changes and just now the last of the dependencies have been updated to Swift 3. In addition to those language changes, it appears all the views are broken / messed up in Xcode 8 so that requires additional rework as well... keep you posted.

**Comment by 4np** [comment]
Fixed in [version 1.0.0](https://github.com/4np/UitzendingGemist/releases/tag/1.0.0) 🙌🏻 (_Xcode 8, tvOS 10, Swift 3_)

**Comment by mischamol** [comment]
Great!!! Many thanks!!!

**Comment by BartHM** [comment]
Super! 👍👍

**Comment by TookiTheGreat** [comment]
Installed 1.0.0 without any issues. It runs flawlessly. My wife and I are very, very grateful to you for making this app.

**Comment by TookiTheGreat** [comment]
One question: there are quite a few programs that have regional protection in place. Does anyone know if there is a way to do IP-address cloaking/spoofing on the Apple TV?

**Comment by 4np** [comment]
My pleasure @TookiTheGreat, glad that you like it 👍 

Regarding the regional limitations, nor the app or Apple TV itself imposes them, it's the NPO (the Dutch Public Broadcaster) who enforces those regional checks and just will not provide the stream when you are in a locale that is not authorised to watch it. In that respect doing cloaking / spoofing with your Apple TV does not work.

A possible solution might be to route all NPO traffic over a VPN to The Netherlands, but that requires you to have a VPN connection to The Netherlands, and your network needs to be setup to route all traffic to the NPO over the VPN. While technically possible, it is not something that is doable for the general public.

Another way could be to set up a [SOCKS proxy over SSH](https://www.digitalocean.com/community/tutorials/how-to-route-web-traffic-securely-without-a-vpn-using-a-socks-tunnel) and then configure the Apple TV 4 to use the SOCKS proxy (which it looks like can be done using a [configuration profile](https://support.apple.com/en-us/HT202577)). Downside is you need to start this tunnel whenever you want to use your Apple TV and all your Apple TV traffic will go though the SSH tunnel (also the iTunes store, etcetera) and you need a *nix server in the Netherlands (and that will not charge you for large amounts of traffic ;).

``` shell
ssh -g -D 1080 user@a.dutch.server.nl
```

From the UI perspective, the APIs _do_ provide location restriction information, but at this moment [I am ignoring it](https://github.com/4np/UitzendingGemist/blob/master/NPOKit/NPOKit/NPORestriction.swift#L44). It would be good to perhaps show a visual queue that a particular episode is regionally locked down. Although it does not help you watch particular episodes, it is at least a convenience that it will show you what will not be viewable... I did get the impression those API results did not always properly reflect the regional checks on the video server, but I might be wrong.

What country are you in @TookiTheGreat ? And do you have a couple of examples of Episodes that do not work for you? Then I might be able to take a closer look...

**Comment by TookiTheGreat** [comment]
Hi Jeroen,

I was afraid it would be somewhat complicated. We're in Australia and use HMA (Hide My Ass) on our laptops to access Dutch programs with regional restrictions. It works, but is not as nice as watching programs on the big screen TV. As you say: it would be slightly more elegant to see a warning when programs are restricted, rather than just nothing happening when we try to play them. On the other hand, we're used to this behavior and it is by no means a show stopper.

I will ask my wife to give me some examples and then I'll get back to you. I seem to remember she tried to watch a French detective series recently that didn't work.
